manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: lexxbyte
      url-base: https://github.com/lexxbyte
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-nice-oled
      remote: lexxbyte
      revision: 5164a9625c2a3c1c8d20bce896fc8bf9271a1c39
  self:
    path: config
